css-brochure-form | Daniel Hong
daniel-sj-hong/c0521-code-solutions pull request #15
Opened 2021-05-06 17:02 UTC by daniel-sj-hong

![Screenshot 2021-05-06 095629](https://user-images.githubusercontent.com/80491609/117337338-1a7ec900-ae52-11eb-84e1-79620fb40fae.png)

2021-05-06 18:58 UTC, codingcodymiller requested changes
Great start here, man! A few notes for you:

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/index.html
> +      <h2>HOW MANY ENGINEERS ARE YOU HIRING IN THE NEXT 6 MONTHS?</h2>
I would make this a `label` element rather than a `h2`

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/index.html
> +      <h2>WHERE ARE YOU HIRING?</h2>
I would make this a `label` element rather than a `h2`

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/index.html
> +      <h2>NAME</h2>
I would make this a `label` element rather than a `h2`

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/index.html
> +      <h2>COMPANY EMAIL</h2>
I would make this a `label` element rather than a `h2`

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin: auto;
These can be removed, `text-align` will take care of this for you 👍

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Medium.woff2') format('woff2');
These are unnecessary, they are only needed in the `@font-face` rule, which you don't need to worry about for now 👍

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Medium.woff2') format('woff2');
These are unnecessary, they are only needed in the `@font-face` rule, which you don't need to worry about for now 👍

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  border-style: groove;
This should be `solid`

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  src: url('AtlasGrotesk-Light-Web.woff2') format('woff2');
These are unnecessary, they are only needed in the `@font-face` rule, which you don't need to worry about for now 👍

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Regular.woff2') format('woff2');
These are unnecessary, they are only needed in the `@font-face` rule, which you don't need to worry about for now 👍

2021-05-06 18:58 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Medium.woff2') format('woff2');
These are unnecessary, they are only needed in the `@font-face` rule, which you don't need to worry about for now 👍

2021-05-07 00:27 UTC, daniel-sj-hong commented
![Screenshot 2021-05-06 172608](https://user-images.githubusercontent.com/80491609/117381174-52a4fc80-ae90-11eb-9281-79c06bfeb91e.png)

2021-05-07 00:36 UTC, codingcodymiller requested changes
This is looking much better! A few more notes for you:

2021-05-07 00:36 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  border-style: groove;
This still needs to be addressed

2021-05-07 00:36 UTC, codingcodymiller commented on css-brochure-form/index.html
> +      <label>HOW MANY ENGINEERS ARE YOU HIRING IN THE NEXT 6 MONTHS?</label>
You should apply a `for` attribute to each of your `label` elements that matches to its form control element.

2021-05-07 16:53 UTC, codingcodymiller approved these changes
Nice work, dude!!

2021-05-07 16:54 UTC, merged